apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-fast
  namespace: familyai
  labels:
    app: chat-fast
    service: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-fast
  template:
    metadata:
      labels:
        app: chat-fast
        service: vllm
    spec:
      containers:
      - name: vllm
        image: nvcr.io/nvidia/tritonserver:25.08-vllm-python-py3
        command:
        - python3
        - -m
        - vllm.entrypoints.openai.api_server
        args:
        - --model
        - $(MODEL)
        - --quantization
        - $(QUANTIZATION)
        - --gpu-memory-utilization
        - $(GPU_MEMORY_UTILIZATION)
        - --max-model-len
        - "32768"
        - --tensor-parallel-size
        - $(TENSOR_PARALLEL_SIZE)
        - --host
        - "0.0.0.0"
        - --port
        - "8000"
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: MODEL
          valueFrom:
            configMapKeyRef:
              name: familyai-models
              key: CHAT_FAST_MODEL
        - name: QUANTIZATION
          valueFrom:
            configMapKeyRef:
              name: familyai-config
              key: VLLM_QUANTIZATION
        - name: GPU_MEMORY_UTILIZATION
          valueFrom:
            configMapKeyRef:
              name: familyai-config
              key: VLLM_GPU_MEMORY_UTILIZATION
        - name: TENSOR_PARALLEL_SIZE
          valueFrom:
            configMapKeyRef:
              name: familyai-config
              key: VLLM_TENSOR_PARALLEL_SIZE
        - name: HF_HOME
          valueFrom:
            configMapKeyRef:
              name: familyai-config
              key: HF_HOME
        - name: HTTP_PROXY
          valueFrom:
            configMapKeyRef:
              name: familyai-config
              key: PROXY_URL
        - name: HTTPS_PROXY
          valueFrom:
            configMapKeyRef:
              name: familyai-config
              key: PROXY_URL
        volumeMounts:
        - name: models
          mountPath: /data/huggingface
        resources:
          requests:
            memory: "8Gi"
            nvidia.com/gpu: 1
          limits:
            memory: "16Gi"
            nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: familyai-models-pvc
      nodeSelector:
        nvidia.com/gpu: "true"
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule

---
apiVersion: v1
kind: Service
metadata:
  name: chat-fast
  namespace: familyai
spec:
  selector:
    app: chat-fast
  ports:
  - port: 8000
    targetPort: 8000
    name: http
