# Whisper ASR Configuration

# Model settings
model:
  name: "openai/whisper-small"  # Can be: tiny, base, small, medium, large
  device: "cuda"  # cuda or cpu
  compute_type: "float16"  # float16, int8, or float32

# Language settings
language:
  default: "auto"  # Auto-detect language, or specify: en, zh, ja, etc.
  task: "transcribe"  # transcribe or translate

# Performance settings
performance:
  beam_size: 5
  best_of: 5
  temperature: 0.0
  vad_filter: true  # Voice Activity Detection
  vad_threshold: 0.5

# Audio processing
audio:
  sample_rate: 16000
  max_duration: 300  # Maximum audio duration in seconds

# API settings
api:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  log_level: "info"

# Cache settings
cache:
  enabled: true
  directory: "/data/huggingface"
